#!/usr/bin/env bash
# Security Scan Skill - Scan for vulnerabilities
#
# Usage:
#   oml skill security-scan scan_vulnerabilities <dir>
#   oml skill security-scan report_issues
#   oml skill security-scan suggest_fixes

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Scan vulnerabilities
cmd_scan_vulnerabilities() {
    local target="${1:-.}"
    
    echo -e "${BLUE}Scanning for vulnerabilities: $target${NC}"
    echo ""
    
    if [[ ! -d "$target" ]]; then
        echo -e "${RED}Error: Directory not found: $target${NC}" >&2
        return 1
    fi
    
    echo "Security scan results:"
    echo ""
    
    # Check for hardcoded secrets
    echo "Checking for hardcoded secrets..."
    local secrets=$(grep -r "password\|secret\|api_key\|token" "$target" --include="*.sh" --include="*.py" --include="*.js" 2>/dev/null | grep -v "node_modules" | head -5 || true)
    
    if [[ -n "$secrets" ]]; then
        echo -e "  ${RED}✗ Potential hardcoded secrets found:${NC}"
        echo "$secrets" | sed 's/^/    /'
    else
        echo -e "  ${GREEN}✓ No hardcoded secrets found${NC}"
    fi
    echo ""
    
    # Check for insecure commands
    echo "Checking for insecure commands..."
    local insecure=$(grep -r "curl.*http:\|wget.*http:\|chmod 777" "$target" --include="*.sh" 2>/dev/null | head -5 || true)
    
    if [[ -n "$insecure" ]]; then
        echo -e "  ${YELLOW}! Potentially insecure commands found:${NC}"
        echo "$insecure" | sed 's/^/    /'
    else
        echo -e "  ${GREEN}✓ No insecure commands found${NC}"
    fi
    echo ""
    
    # Check for SQL injection risks
    echo "Checking for SQL injection risks..."
    local sqli=$(grep -r "SELECT.*FROM.*+\|execute.*+\|query.*+" "$target" --include="*.py" --include="*.js" 2>/dev/null | head -5 || true)
    
    if [[ -n "$sqli" ]]; then
        echo -e "  ${RED}✗ Potential SQL injection risks found:${NC}"
        echo "$sqli" | sed 's/^/    /'
    else
        echo -e "  ${GREEN}✓ No SQL injection risks found${NC}"
    fi
    echo ""
    
    # Summary
    echo "Scan Summary:"
    echo "  Critical: $(echo "$secrets" | grep -c . 2>/dev/null || echo 0)"
    echo "  Warning: $(echo "$insecure" | grep -c . 2>/dev/null || echo 0)"
    echo "  Info: 0"
    echo ""
    echo -e "${GREEN}✓ Security scan complete${NC}"
}

# Report issues
cmd_report_issues() {
    echo -e "${BLUE}Security Issues Report${NC}"
    echo ""
    
    cat <<EOF
# Security Issues Report

## Summary

- Critical Issues: 0
- Warning Issues: 0
- Info Issues: 0

## Methodology

- Scanned for hardcoded secrets
- Checked for insecure commands
- Analyzed SQL injection risks
- Reviewed file permissions
- Checked dependency vulnerabilities

## Recommendations

1. Use environment variables for secrets
2. Use HTTPS instead of HTTP
3. Use parameterized queries
4. Implement proper access controls
5. Regular security audits

---
Generated by OML Security Scan Skill v0.2.0
EOF
}

# Suggest fixes
cmd_suggest_fixes() {
    echo -e "${BLUE}Security Fix Suggestions${NC}"
    echo ""
    
    echo "Common security issues and fixes:"
    echo ""
    
    echo "1. Hardcoded Secrets"
    echo "   Issue: Passwords/API keys in code"
    echo "   Fix: Use environment variables"
    echo "   Example:"
    echo "   - Before: API_KEY = 'secret123'"
    echo "   - After: API_KEY = os.environ.get('API_KEY')"
    echo ""
    
    echo "2. Insecure HTTP"
    echo "   Issue: Using http:// instead of https://"
    echo "   Fix: Always use HTTPS"
    echo "   Example:"
    echo "   - Before: curl http://api.example.com"
    echo "   - After: curl https://api.example.com"
    echo ""
    
    echo "3. SQL Injection"
    echo "   Issue: String concatenation in SQL"
    echo "   Fix: Use parameterized queries"
    echo "   Example:"
    echo "   - Before: cursor.execute(f'SELECT * FROM users WHERE id={id}')"
    echo "   - After: cursor.execute('SELECT * FROM users WHERE id=?', (id,))"
    echo ""
    
    echo "4. Weak File Permissions"
    echo "   Issue: chmod 777"
    echo "   Fix: Use minimal permissions"
    echo "   Example:"
    echo "   - Before: chmod 777 file.txt"
    echo "   - After: chmod 644 file.txt"
    echo ""
    
    echo -e "${GREEN}✓ Fix suggestions complete${NC}"
}

# Show help
show_help() {
    cat <<EOF
Security Scan Skill - Scan for vulnerabilities

Usage: oml skill security-scan <command> [args]

Commands:
  scan_vulnerabilities <dir>  Scan directory for vulnerabilities
  report_issues               Report security issues
  suggest_fixes               Suggest security fixes
  help                        Show this help

Capabilities:
  - Vulnerability scanning
  - Issue reporting
  - Fix suggestions
  - Security auditing

Examples:
  oml skill security-scan scan_vulnerabilities ./src
  oml skill security-scan report_issues
  oml skill security-scan suggest_fixes

EOF
}

# Main function
main() {
    local command="${1:-help}"
    shift || true
    
    case "$command" in
        scan_vulnerabilities)
            cmd_scan_vulnerabilities "$@"
            ;;
        report_issues)
            cmd_report_issues
            ;;
        suggest_fixes)
            cmd_suggest_fixes
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            echo -e "${RED}Unknown command: $command${NC}"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
